// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProject_klas3_groep4;

#nullable disable

namespace WebProject_klas3_groep4.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251009210255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("WebProject_klas3_groep4.VeilingDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AantalProducten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bechrijving")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HuidigeSituatieVanVeiling")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KlokLocatie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StarTijd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VeilingmeesterDBID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("VeilingmeesterDBID");

                    b.ToTable("Veilingen");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.models.GebruikerDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Telefoonnummer")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Gebruikers");

                    b.HasDiscriminator().HasValue("GebruikerDB");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebProject_klas3_groep4.models.LotDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GebeurtenisDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("GewensteLocatie")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VeilingDBID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeilingID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("VeilingDBID");

                    b.ToTable("LotDB");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.VeilingmeesterDB", b =>
                {
                    b.HasBaseType("WebProject_klas3_groep4.models.GebruikerDB");

                    b.Property<string>("VeilingVestiging")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("VeilingmeesterDB");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.VeilingDB", b =>
                {
                    b.HasOne("WebProject_klas3_groep4.VeilingmeesterDB", null)
                        .WithMany("Veilingen")
                        .HasForeignKey("VeilingmeesterDBID");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.models.LotDB", b =>
                {
                    b.HasOne("WebProject_klas3_groep4.VeilingDB", null)
                        .WithMany("Lists")
                        .HasForeignKey("VeilingDBID");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.VeilingDB", b =>
                {
                    b.Navigation("Lists");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.VeilingmeesterDB", b =>
                {
                    b.Navigation("Veilingen");
                });
#pragma warning restore 612, 618
        }
    }
}
