// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProject_klas3_groep4;

#nullable disable

namespace WebProject_klas3_groep4.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251119103821_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebProject_klas3_groep4.VeilingDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AantalProducten")
                        .HasColumnType("int");

                    b.Property<string>("Bechrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HuidigeSituatieVanVeiling")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KlokLocatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StarTijd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDatum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VeilingmeesterDBID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VeilingmeesterDBID");

                    b.ToTable("Veilingen");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.models.GebruikerDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paswoord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefoonnummer")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Gebruikers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("GebruikerDB");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebProject_klas3_groep4.models.productDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AanvoerderDBID")
                        .HasColumnType("int");

                    b.Property<string>("Beschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Gewicht")
                        .HasColumnType("float");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("int");

                    b.Property<int>("MinimalePrijs")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Oogstdatum")
                        .HasColumnType("date");

                    b.Property<int>("Potmaat")
                        .HasColumnType("int");

                    b.Property<double>("Steellengte")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("AanvoerderDBID");

                    b.ToTable("product");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.VeilingmeesterDB", b =>
                {
                    b.HasBaseType("WebProject_klas3_groep4.models.GebruikerDB");

                    b.Property<string>("VeilingVestiging")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("VeilingmeesterDB");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.models.AanvoerderDB", b =>
                {
                    b.HasBaseType("WebProject_klas3_groep4.models.GebruikerDB");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedrijfEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedrijfTelefoonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KvkNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaamVanBedrijf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AanvoerderDB");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.models.KoperDB", b =>
                {
                    b.HasBaseType("WebProject_klas3_groep4.models.GebruikerDB");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankGegevens")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Gebruikers", t =>
                        {
                            t.Property("Adres")
                                .HasColumnName("KoperDB_Adres");

                            t.Property("Postcode")
                                .HasColumnName("KoperDB_Postcode");
                        });

                    b.HasDiscriminator().HasValue("KoperDB");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.VeilingDB", b =>
                {
                    b.HasOne("WebProject_klas3_groep4.VeilingmeesterDB", null)
                        .WithMany("Veilingen")
                        .HasForeignKey("VeilingmeesterDBID");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.models.productDB", b =>
                {
                    b.HasOne("WebProject_klas3_groep4.models.AanvoerderDB", null)
                        .WithMany("prodcten")
                        .HasForeignKey("AanvoerderDBID");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.VeilingmeesterDB", b =>
                {
                    b.Navigation("Veilingen");
                });

            modelBuilder.Entity("WebProject_klas3_groep4.models.AanvoerderDB", b =>
                {
                    b.Navigation("prodcten");
                });
#pragma warning restore 612, 618
        }
    }
}
